server:
  port: 8081
  servlet:
    context-path: /resource-server

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/amazonreviewsanalyzer
          jwk-set-uri: http://localhost:8083/auth/realms/amazonreviewsanalyzer/protocol/openid-connect/certs
